apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 10-grafana.yaml
  - 20-datasource.yaml
  - 30-dashboards/cluster-overview.yaml
  - 30-dashboards/controller-manager.yaml
  - 30-dashboards/etcd-health.yaml
  - 30-dashboards/kube-apiserver.yaml
  - 30-dashboards/node-resources.yaml
